export const PROJECT_DATE = new Intl.DateTimeFormat("en-GB", {
  day: "numeric",
  month: "long",
  year: "numeric",
}).format(new Date());

export const PAKISTAN_COORDINATE_BOUNDS = {
  minimumLatitude: 23.5,
  maximumLatitude: 37.1,
  minimumLongitude: 60.8,
  maximumLongitude: 77.9,
};

export const SCENARIOS = [
  {
    id: "jhimpir-wind",
    name: "Wind",
    shortName: "Wind",
    technologyLabel: "Onshore wind",
    locationLabel: "Jhimpir, Sindh",
    evidence: "Medium",
    source: "Open-Meteo ERA5",
    color: "#5a2617",
    defaultCapex: 976,
    defaultPrice: 60,
    fallback: {
      generationP90: 320151.31,
      generationP50: 341978.35,
      generationP10: 379292.15,
      lcoe: 43.1411,
      irr: 0.163388,
      resourceCv: 0.063,
    },
    request: {
      scenario_id: "jhimpir-wind",
      technology: "wind",
      location: { name: "Jhimpir, Sindh", latitude: 25.025, longitude: 67.95 },
      capacity_mw: 100,
      lifetime_years: 30,
      annual_degradation_rate: 0,
      financial: {
        capex_per_kw: 976,
        fixed_opex_per_kw_year: 44,
        variable_opex_per_mwh: 0,
        electricity_price_per_mwh: 60,
        discount_rate: 0.1,
        electricity_price_growth_rate: 0,
        opex_growth_rate: 0,
      },
      resource: {
        start_date: "2015-01-01",
        end_date: "2024-12-31",
        provider: "auto",
        minimum_year_completeness: 0.99,
      },
      wind: {
        hub_height_m: 100,
        cut_in_speed_ms: 3,
        rated_speed_ms: 9.8127,
        cut_out_speed_ms: 25.01,
        turbine_rated_power_mw: 3.37,
        availability: 0.95,
        wind_shear_exponent: 0.142857,
        reference_air_density_kg_m3: 1.225,
      },
    },
  },
  {
    id: "jhimpir-solar",
    name: "Solar",
    shortName: "Solar",
    technologyLabel: "Utility-scale PV",
    locationLabel: "Jhimpir, Sindh",
    evidence: "Medium",
    source: "Open-Meteo ERA5",
    color: "#bd4b1e",
    defaultCapex: 667,
    defaultPrice: 60,
    fallback: {
      generationP90: 189366,
      generationP50: 194705.06,
      generationP10: 196659.8,
      lcoe: 50.3913,
      irr: 0.13071,
      resourceCv: 0.012,
    },
    request: {
      scenario_id: "jhimpir-solar",
      technology: "solar",
      location: { name: "Jhimpir, Sindh", latitude: 25.025, longitude: 67.95 },
      capacity_mw: 100,
      lifetime_years: 30,
      annual_degradation_rate: 0.007,
      financial: {
        capex_per_kw: 667,
        fixed_opex_per_kw_year: 22,
        variable_opex_per_mwh: 0,
        electricity_price_per_mwh: 60,
        discount_rate: 0.1,
        electricity_price_growth_rate: 0,
        opex_growth_rate: 0,
      },
      resource: {
        start_date: "2015-01-01",
        end_date: "2024-12-31",
        provider: "auto",
        minimum_year_completeness: 0.99,
      },
      solar: {
        tilt_deg: 25,
        azimuth_deg: 180,
        system_losses: 0.141,
        reference_irradiance_wm2: 1000,
        reference_cell_temperature_c: 25,
        temperature_coefficient_per_c: -0.004,
      },
    },
  },
  {
    id: "karachi-wave",
    name: "Wave",
    shortName: "Wave",
    technologyLabel: "Wave energy (research)",
    locationLabel: "Karachi Coast",
    evidence: "Low",
    source: "Open-Meteo ERA5-Ocean fallback",
    color: "#c78a2a",
    defaultCapex: 5000,
    defaultPrice: 60,
    fallback: {
      generationP90: 36034.96,
      generationP50: 39235.95,
      generationP10: 46791.47,
      lcoe: 1921.4343,
      irr: null,
      resourceCv: 0.125,
    },
    request: {
      scenario_id: "karachi-wave",
      technology: "wave",
      location: { name: "Arabian Sea offshore Karachi", latitude: 24.5, longitude: 66.5 },
      capacity_mw: 100,
      lifetime_years: 25,
      annual_degradation_rate: 0.01,
      financial: {
        capex_per_kw: 5000,
        fixed_opex_per_kw_year: 150,
        variable_opex_per_mwh: 0,
        electricity_price_per_mwh: 60,
        discount_rate: 0.1,
        electricity_price_growth_rate: 0,
        opex_growth_rate: 0,
      },
      resource: {
        start_date: "2015-01-01",
        end_date: "2024-12-31",
        provider: "auto",
        minimum_year_completeness: 0.99,
      },
      wave: {
        conversion_efficiency: 0.3,
        capture_width_m: 20,
        device_rated_power_mw: 1,
        availability: 0.9,
      },
    },
  },
];

export const INITIAL_MARKET_CONTEXT = {
  default_currency: "USD",
  resource_period: "2015–2024",
  cost_basis_label: "IRENA 2025 global benchmarks (2025 USD)",
  fx: {
    rate: 277.5,
    as_of: "2026-08-28T00:00:00Z",
    source_name: "Published Pakistan interbank close (bundled fallback)",
    source_url: "https://www.brecorder.com/markets/currency/3198",
    official_reference_url: "https://www.sbp.org.pk/ecodata/rates/m2m/Months.asp",
    is_live: false,
    is_stale: false,
    warning: "Indicative display conversion only. Verify the latest official rate before use.",
  },
};

export function scenarioInputsFromDefaults() {
  return Object.fromEntries(
    SCENARIOS.map((scenario) => [
      scenario.id,
      {
        locationName: scenario.request.location.name,
        latitude: scenario.request.location.latitude,
        longitude: scenario.request.location.longitude,
        capacity: scenario.request.capacity_mw,
        lifetime: scenario.request.lifetime_years,
        degradationPct: scenario.request.annual_degradation_rate * 100,
        capex: scenario.defaultCapex,
        fixedOpex: scenario.request.financial.fixed_opex_per_kw_year,
        variableOpex: scenario.request.financial.variable_opex_per_mwh,
        electricityPrice: scenario.defaultPrice,
        discountRatePct: scenario.request.financial.discount_rate * 100,
        priceGrowthPct: scenario.request.financial.electricity_price_growth_rate * 100,
        opexGrowthPct: scenario.request.financial.opex_growth_rate * 100,
        startDate: scenario.request.resource.start_date,
        endDate: scenario.request.resource.end_date,
        provider: scenario.request.resource.provider,
        solarTilt: scenario.request.solar?.tilt_deg ?? "",
        solarAzimuth: scenario.request.solar?.azimuth_deg ?? "",
        solarLossPct: scenario.request.solar ? Number((scenario.request.solar.system_losses * 100).toFixed(3)) : "",
        windHubHeight: scenario.request.wind?.hub_height_m ?? "",
        windAvailabilityPct: scenario.request.wind ? scenario.request.wind.availability * 100 : "",
        windShear: scenario.request.wind?.wind_shear_exponent ?? "",
        waveEfficiencyPct: scenario.request.wave ? scenario.request.wave.conversion_efficiency * 100 : "",
        waveCaptureWidth: scenario.request.wave?.capture_width_m ?? "",
        waveAvailabilityPct: scenario.request.wave ? scenario.request.wave.availability * 100 : "",
      },
    ]),
  );
}

export function buildAnalysisRequest(scenario, inputs) {
  const latitude = Number(inputs.latitude);
  const longitude = Number(inputs.longitude);
  const enteredName = String(inputs.locationName || "").trim();
  return {
    ...scenario.request,
    location: {
      name: enteredName || `Pakistan site ${latitude.toFixed(4)}, ${longitude.toFixed(4)}`,
      latitude,
      longitude,
    },
    capacity_mw: Number(inputs.capacity),
    lifetime_years: Number(inputs.lifetime),
    annual_degradation_rate: Number(inputs.degradationPct) / 100,
    financial: {
      ...scenario.request.financial,
      capex_per_kw: Number(inputs.capex),
      fixed_opex_per_kw_year: Number(inputs.fixedOpex),
      variable_opex_per_mwh: Number(inputs.variableOpex),
      electricity_price_per_mwh: Number(inputs.electricityPrice),
      discount_rate: Number(inputs.discountRatePct) / 100,
      electricity_price_growth_rate: Number(inputs.priceGrowthPct) / 100,
      opex_growth_rate: Number(inputs.opexGrowthPct) / 100,
    },
    resource: {
      ...scenario.request.resource,
      start_date: inputs.startDate,
      end_date: inputs.endDate,
      provider: inputs.provider,
    },
    solar: scenario.request.solar ? {
      ...scenario.request.solar,
      tilt_deg: Number(inputs.solarTilt),
      azimuth_deg: Number(inputs.solarAzimuth),
      system_losses: Number(inputs.solarLossPct) / 100,
    } : null,
    wind: scenario.request.wind ? {
      ...scenario.request.wind,
      hub_height_m: Number(inputs.windHubHeight),
      availability: Number(inputs.windAvailabilityPct) / 100,
      wind_shear_exponent: Number(inputs.windShear),
    } : null,
    wave: scenario.request.wave ? {
      ...scenario.request.wave,
      conversion_efficiency: Number(inputs.waveEfficiencyPct) / 100,
      capture_width_m: Number(inputs.waveCaptureWidth),
      availability: Number(inputs.waveAvailabilityPct) / 100,
    } : null,
  };
}

export function fallbackRows() {
  return SCENARIOS.map((scenario) => ({
    scenario_id: scenario.id,
    technology: scenario.request.technology,
    location_name: scenario.request.location.name,
    requested_latitude: scenario.request.location.latitude,
    requested_longitude: scenario.request.location.longitude,
    resolved_latitude: scenario.request.location.latitude,
    resolved_longitude: scenario.request.location.longitude,
    resource_source_name: scenario.source,
    resource_dataset_name: scenario.source,
    capacity_mw: scenario.request.capacity_mw,
    project_irr: scenario.fallback.irr,
    lcoe_usd_per_mwh: scenario.fallback.lcoe,
    resource_coefficient_of_variation: scenario.fallback.resourceCv,
    p90_generation_mwh: scenario.fallback.generationP90,
    p50_generation_mwh: scenario.fallback.generationP50,
    p10_generation_mwh: scenario.fallback.generationP10,
  }));
}
